### ISSUE TITLE
Setup database bug

### ISSUE THREAD

**Issue by davidecrs** [iquasere/reCOGnizer#15] opened 2023-09-07 17:17 UTC
Hi,

I was setting up the database before running recognizer on prodigal predicted orf (on multiple samples), so I have run the following command:
```
recognizer --download-resources --resources-directory .
```

but I have encountered these errors, which seem to prevent the next step of running multiple recognizer on different predicted orf.
```
cat: 'reCOGnizer_results/blast/KOG_*_aligned.blast': No such file or directory
2023-09-07 17:12:30: Organizing annotation results
cat: 'reCOGnizer_results/blast/CDD_*_aligned.blast': No such file or directory
[1/8] Handling CDD annotation
cat: 'reCOGnizer_results/blast/Pfam_*_aligned.blast': No such file or directory
[2/8] Handling Pfam annotation
cat: 'reCOGnizer_results/blast/NCBIfam_*_aligned.blast': No such file or directory
[3/8] Handling NCBIfam annotation
cat: 'reCOGnizer_results/blast/Protein_Clusters_*_aligned.blast': No such file or directory
[4/8] Handling Protein_Clusters annotation
cat: 'reCOGnizer_results/blast/Smart_*_aligned.blast': No such file or directory
[5/8] Handling Smart annotation
cat: 'reCOGnizer_results/blast/TIGRFAM_*_aligned.blast': No such file or directory
[6/8] Handling TIGRFAM annotation
cat: 'reCOGnizer_results/blast/COG_*_aligned.blast': No such file or directory
[7/8] Handling COG annotation
cog2ko not found! Going to build it
join: -:13109: is not sorted: 1001530.BACE01000023_gene1	COG5184
join: ./string2ko.tsv:61: is not sorted: 264203.ZMO1579 K06889
join: input is not in sorted order
cat: 'reCOGnizer_results/blast/KOG_*_aligned.blast': No such file or directory
[8/8] Handling KOG annotation
2023-09-07 17:15:06: reCOGnizer analysis finished in 00h17m04s


```

Do you know how can I solve this issue?

Best,
Davide

**Comment by iquasere** [comment] 2023-09-15 09:18
Greetings! The warnings you are getting report that the annotation results can't be found, which makes sense since you aren't annotating anything, just downloading the resources. You can ignore those safely, as long as they don't show up when you annotate sequences specified through the `--file` parameter.

However, when I implemented the option to download the resources prior to annotation, it was supposed for reCOGnizer to stop after downloading. It shouldn't search for annotation results, since those are not supposed to be produced.

I have reproduced this on my end, with the latest version of reCOGnizer (`1.9.2`). Again, the warnings are not problematic since the resources were downloaded correctly, but it's still a bug that will be fixed today.

**Comment by davidecrs** [comment] 2023-11-30 15:32
Hi @iquasere ,

when downloading the database, the following files `recognizer.log` and `taxonomy.rdf` are saved in the working directory even if I'm executing the following code
```
(cd temp/recognizer_db & recognizer --resources-directory temp/recognizer_db --download-resources --output temp/recognizer_db/null_results )
```

After the execution I have,
```bash
$ ls -1 

recognizer.log
taxonomy.rdf
temp
```

Is it possible to redirect the path of `recognizer.log` and `taxonomy.rdf`  to the same `-resources-directory` path?

`recognizer version: 1.9.2`

Best regards,
Davide

**Comment by davidecrs** [comment] 2023-12-07 08:58
Hi @iquasere ,

sorry for the double message, I also wanted to add that by running the following command
```
recognizer --resources-directory recognizer_extdb --download-resources --output recognizer_extdb/null_results
```
the exit code is 1

**Comment by iquasere** [comment] 2023-12-22 11:58
Was very busy on these last couple weeks, but am now tackling this issue. My goal is to make downloading reCOGnizer's resources much simpler. For now the plan is to use the `recognizer_dwnl.timestamp` file as evidence that the databses have already been downloaded, and if the file is present, skip downloading, if not, download everything.

This approach puts more responsibility on the user side, since if some file is altered everything else will have to be downloaded again (unless some backup was made). It will, however, make the entire databases download process much simpler, and less prone to errors. Such as the one you have identified.

**Closed** 2023-12-27 15:07 UTC
Labels: bug

**Comment by iquasere** [comment] 2023-12-28 11:50
With [release `1.10`](https://github.com/iquasere/reCOGnizer/releases/tag/1.10.0), all these issues were approached, together with many others. Database installation is now much simpler, and actually can be almost ignored. Just make sure `-rd` parameter is set to the desired value, or don't even use it if you have no problems downloading databases to your folder.

**Comment by davidecrs** [comment] 2023-12-28 12:55
Many thanks. I will try this new version.

**Comment by davidecrs** [comment] 2023-12-29 10:39
Hi @iquasere ,

I tried this new version using
```
recognizer -rd recog_db/
```
it worked fine. However, the exit status code is 1 (I don't know if you're interested, but in a pipeline, this may interrupt the workflow).

Also the files `recognizer.log` and `taxonomy.rdf` are no longer created (I assume correctly).

In any case, thanks again for these improvements!

Best regards

**Comment by iquasere** [comment] 2023-12-29 11:18
Strange... it's passing in the [tests](https://github.com/iquasere/reCOGnizer/actions/runs/7347099679) at GitHub, and an exit code other than 0 should trigger a failed test. I am currently updating reCOGnizer in a snakemake pipeline that includes it, let me see if it fails using this last version.

**Comment by SrichandanPadhi** [comment] 2024-03-21 09:45
I am actually going through the same issue, I did not find the file recognizer_dwnl.timestamp in the folder. And if I am downloading the using "recognizer --download-resources --resources-directory resources_directory", following error is displayed.

recognizer: error: argument -dr/--download-resources: expected one argument

**Comment by SrichandanPadhi** [comment] 2024-03-23 04:41
Sorry for delay in replying. 
As instructed, I tried removing --download-resources, it worked, the databases have been downloaded; however, ended with an issue while extracting. Please see the following. A screenshot has been enclosed for your reference and action please.   

tar -xzf cdd.tar.gz --wildcards "*.smp"
2024-03-22 20:58:16: Building taxonomy.tsv
No input file specified. Exiting.



![recognizer issues- 1](https://github.com/iquasere/reCOGnizer/assets/128894160/3c0869fc-9561-4bd1-8706-b94f6fc83840)

**Comment by SrichandanPadhi** [comment] 2024-03-23 07:57
Hey Joao,
Thank you very much, for the suggestion.

Despite the issue, I tried running the annotation using recognizer. Whatever the issues remained during the --download_resources were solved and the missing files were rebuilt very very nice and fine. 

Now I am going to use the KeggCharter using the recognizer output. In case any issues I will let you know. Thanks again.

**Comment by iquasere** [comment] 2024-03-25 16:40
reCOGnzier now doesn't require the command to download resources at all. You can just run it as 
```
recognizer -i input.fasta -o output -rd resources_directory
```
but I do see that this is not obvious in the documentation. Once I have the time, I'll fix that.

Glad you are using it now, together with KEGGCharter. Do let me know if it helps your work, or if you encounter any more problems!

**Comment by SrichandanPadhi** [comment] 2024-03-26 05:22
Yes, sure..thanks for your support.

**Comment by davidecrs** [comment] 2024-03-26 06:49
Hi,

Is it still possible to download the database before running the annotation?

Best regards
